### ISSUE TITLE
visual-studio-code icon missing

### ISSUE THREAD

**Issue by mazid1** [yeyushengfan258/Win11-icon-theme#2]
![image](https://user-images.githubusercontent.com/6582459/127870443-f4ba4bb6-e7b0-48a9-8095-e376ea470eba.png)

This blue icon is missing. The purple icon, which is actually for visual-studio, is being used for visual-studio-code.

**Comment by yeyushengfan258** [comment]
I will fix and modify it, thank you.

**Comment by liulitchi** [comment]
also vscodium icon, it's the opensource version of vscode.

**Comment by yeyushengfan258** [comment]
I need the correct icon name.

**Comment by mazid1** [comment]
The original issue (visual-studio-code icon) is fixed by this commit ed1fb504c384aa0c96cb71d4f560e65525396e91
