### ISSUE TITLE
file explorer kde dolphin "search" icon

### ISSUE THREAD

**Issue by Suryavarman-II** [yeyushengfan258/Win11-icon-theme#62]
The "search for file/folder" button/icon in dolphin is a little bit irritating. The icon has a yellow triangle and it looks like there's something that needs a user attention.
Maybe you can replace that with another "search" symbol?

![Screenshot_20220124_012414](https://user-images.githubusercontent.com/94405857/150736770-20d3c30b-3f41-4fca-82d7-4f9be49fc1b8.png)

**Comment by yeyushengfan258** [comment]
This is my mistake, I will correct it.

**Comment by Suryavarman-II** [comment]
Ok thank you. I made a mistake too, i mean the file explorer "dolphin" in kde plasma and not nautilus.

**Comment by Suryavarman-II** [comment]
It's fixed now. I'll close this issue. Thank you.

**Comment by Suryavarman-II** [comment]
It's fixed now. I'll close this issue. Thank you.
