### ISSUE TITLE
question about licensing

### ISSUE THREAD

**Issue by ckerr** [yeyushengfan258/Win11-icon-theme#75]
Hi, I'm unclear on the licensing of this project. Is the intent that the icon set can only be used in applications that are GPLv3-licensed?

If so, that's fine! Nice to have more GPL projects in the world! But I thought I'd ask for clarification because it's an unusual license to choose for assets that aren't source code.

**Comment by yeyushengfan258** [comment]
Yes, under the GPLv3 license.
